name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "--cfg debug_assertions"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Install riscv64 target
      run: rustup target add riscv64imac-unknown-none-elf
    - name: Build
      run: cargo build --verbose --release --target=riscv64imac-unknown-none-elf
    - name: Run tests
      run: cd tests; cargo test --verbose
