name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  ZERO_LOCK_PATH: ../target/riscv64imac_zba_zbb_zbc_zbs-unknown-ckb-elf/debug/ckb-zero-lock

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Install custom Rust toolchain
      run: curl https://raw.githubusercontent.com/xxuejie/ckb-contract-toolchains/c4b3a52e2f47fcdeb9f7b663f193fec506f7e158/install.sh | bash -s -- 20230710-1
    - name: Build
      run: cargo build --verbose --target=riscv64imac_zba_zbb_zbc_zbs-unknown-ckb-elf
    - name: Run tests
      run: cd tests; cargo test --verbose
